// Generated by https://quicktype.io

declare namespace df {
 
export interface SougoResponse {
    detect:       Detect;
    errorCode:    number;
    message:      string;
    translate:    { [key: string]: string };
    dictionary:   Dictionary;
    sugg:         Sugg[];
    isHasOxford:  boolean;
    isHasChinese: boolean;
}

export interface Detect {
    zly:       string;
    detect:    string;
    errorCode: string;
    language:  string;
    id:        string;
    text:      string;
}

export interface Dictionary {
    zly:     string;
    content: DictionaryContent[];
    dicType: string;
}

export interface DictionaryContent {
    phonetic:          Phonetic[];
    usual:             Usual[];
    is_show_for_vr:    number;
    origin:            string[];
    rarelyWordDict:    RarelyWordDict;
    no_show_char_list: any[];
    word:              string;
    content:           ContentContent[];
}

export interface ContentContent {
    item: Item;
}

export interface Item {
    core:            Core[];
    pos:             string;
    posCoreInfoList: any[];
}

export interface Core {
    index:    string;
    detail:   Detail;
    branch?:  Branch[];
    example?: Detail[];
}

export interface Branch {
    detail:   Detail;
    example?: Detail[];
}

export interface Detail {
    en: string;
    zh: string;
}

export interface Phonetic {
    filename: string;
    text:     string;
    type:     string;
}

export interface RarelyWordDict {
    rarelyWordList:   any[];
    isHaveRarelyWord: number;
}

export interface Usual {
    pos:    string;
    values: string[];
}

export interface Sugg {
    usual: Usual[];
    word:  string;
}

}